import Layout from "../components/Layout"
import ContactMe from '../components/Contact/ContactMe'
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

const Contact = ({children}) => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="ln.ico" />
      </Head>
      <Layout>
        <ContactMe /> 
        {children}
      </Layout>
    </>
  )
} 

export default Contact

export const getStaticProps = async ({locale}) => ({
  props: {
    ...await serverSideTranslations(locale, ['common','contact']),
  },
})