import Layout from "../components/Layout"
import ContactMe from '../components/Contact/ContactMe'
import Head from 'next/head'

const Contact = ({children}) => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="ln.ico" />
      </Head>
      <Layout>
        <ContactMe /> 
        {children}
      </Layout>
    </>
  )
} 

export default Contact