/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Layout from '../components/Layout'
import Hero from '../components/Hero/Hero'
import Divider from '../components/Divider/Divider'
import Main from '../components/Main/Main'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="ln.ico" />
      </Head>
      <Layout>
        <Hero/>  
        <Divider/>
        <Main /> 
      </Layout> 
      
    </>
  )
}
